from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB

EMBEDDING_DIM = 1024

metadata = MetaData()

documents = Table(
    "documents",
    metadata,
    Column("id_norma", Integer, primary_key=True),
    Column("corpus", String(64), nullable=False, index=True),
    Column("tipo_norma", String(64), nullable=False),
    Column("numeros", JSONB, nullable=False),
    Column("organismos", JSONB, nullable=False),
    Column("clase_norma", String(64)),
    Column("fecha_sancion", Date),
    Column("fecha_boletin", Date),
    Column("numero_boletin", Integer),
    Column("titulo_resumido", Text),
    Column("titulo_sumario", Text),
    Column("texto_resumido", Text),
    Column("url_original", Text),
    Column("url_actualizado", Text),
    Column("reason", String(64), nullable=False),
    Column("depth", Integer, nullable=False),
    Column("has_original_text", Boolean, nullable=False),
    Column("has_current_text", Boolean, nullable=False),
    Column("original_source_document_id", Integer),
    Column("front_matter", Text, nullable=False),
    Column("n_articles_original", Integer, nullable=False),
    Column("n_articles_current", Integer, nullable=False),
    Column("n_history_events", Integer, nullable=False),
)

articles = Table(
    "articles",
    metadata,
    Column("id", String(64), primary_key=True),
    Column(
        "document_id",
        Integer,
        ForeignKey("documents.id_norma", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("key", String(32), nullable=False),
    Column("label", String(32), nullable=False),
    Column("number", Integer, nullable=False),
    Column("suffix", String(16)),
    Column("ordinal", Integer, nullable=False),
    Column("heading", Text),
    Column("sections", JSONB, nullable=False),
    Column("annex", String(32)),
)

article_versions = Table(
    "article_versions",
    metadata,
    Column("id", String(80), primary_key=True),
    Column(
        "article_id",
        String(64),
        ForeignKey("articles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column(
        "document_id",
        Integer,
        ForeignKey("documents.id_norma", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("version_kind", String(16), nullable=False),
    Column("text", Text, nullable=False),
    Column("text_with_notes", Text, nullable=False),
    Column("status", String(16), nullable=False),
    Column("effective_from", Date),
    Column("effective_until", Date),
    Column("modification_kind", String(32)),
    Column("modified_by_tipo", String(64)),
    Column("modified_by_numero", String(32)),
    Column("modified_by_article", String(32)),
    Column("source_document_id", Integer, nullable=False),
    Column("source_url", Text),
    Column("text_sha256", String(64), nullable=False),
    Column("unchanged_from_original", Boolean),
    Column("similarity_to_original", Float),
    Index("article_versions_status_from", "status", "effective_from"),
)

relations = Table(
    "relations",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("corpus", String(64), nullable=False, index=True),
    Column("source_id", Integer, nullable=False, index=True),
    Column("target_id", Integer, nullable=False, index=True),
    Column("kind", String(32), nullable=False),
    Column("evidence", String(32), nullable=False),
    Column("tipo", String(64)),
    Column("numero", String(32)),
    Column("organismo", Text),
    Column("fecha_boletin", Date),
    Column("tema", Text),
    Column("descripcion", Text),
    UniqueConstraint("source_id", "target_id", "kind", "evidence", name="relations_unique_edge"),
)

history = Table(
    "history",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column(
        "document_id",
        Integer,
        ForeignKey("documents.id_norma", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("article_key", String(32)),
    Column("article_label", String(32)),
    Column("kind", String(32), nullable=False),
    Column("by_tipo", String(64)),
    Column("by_numero", String(32)),
    Column("by_article", String(32)),
    Column("bo_date", Date),
    Column("vigencia", Text),
    Column("raw", Text, nullable=False),
)

article_references = Table(
    "article_references",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column(
        "source_article_id",
        String(64),
        ForeignKey("articles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column(
        "target_article_id",
        String(64),
        ForeignKey("articles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("kind", String(32), nullable=False),
    Column("evidence", Text, nullable=False),
    UniqueConstraint("source_article_id", "target_article_id", name="uq_article_reference"),
)

feedback = Table(
    "feedback",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("trace_id", String(32), nullable=False, index=True),
    Column("question", Text, nullable=False),
    Column("answer", Text),
    Column("label", String(32), nullable=False),
    Column("comment", Text),
    Column("reviewer", String(64)),
    Column("sources", JSONB),
    Column("expected_articles", JSONB),
    Column("retrieved_articles", JSONB),
    Column("as_of", Date),
    Column("historical", Boolean),
    Column("conversation_id", String(36), index=True),
)

chunks = Table(
    "chunks",
    metadata,
    Column("id", String(96), primary_key=True),
    Column(
        "version_id",
        String(80),
        ForeignKey("article_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("article_id", String(64), nullable=False, index=True),
    Column(
        "document_id",
        Integer,
        ForeignKey("documents.id_norma", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("chunk_index", Integer, nullable=False),
    Column("context_prefix", Text, nullable=False),
    Column("text", Text, nullable=False),
    Column("embed_text", Text, nullable=False),
    Column("token_estimate", Integer, nullable=False),
    Column("embedding", Vector(EMBEDDING_DIM)),
    Column("embedding_model", String(128)),
    Column("created_at", DateTime(timezone=True), server_default=func.now(), nullable=False),
)
